services:
  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: calendar_db
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data

  api:
    build:
      context: .
      target: base
      dockerfile: Dockerfile
    command: sh -c "yarn start:dev"
    ports:
      - 127.0.0.1:3037:3037
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev
    env_file:
      - ./.env
      - ./.env.docker
    depends_on:
      db:
        condition: service_started

  api_prod:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    command: sh -c "yarn start:prod"
    ports:
      - 127.0.0.1:3037:3037
    profiles:
      - prod
    depends_on:
      db:
        condition: service_started
