openapi: 3.0.0
info:
  title: Easy Peasy Calendar API
  version: "1.0.0"
  description: API for managing calendars and calendar entries.
paths:
  /calendars:
    get:
      summary: Get list of calendars
      operationId: getCalendars
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  offset:
                    type: integer
                  limit:
                    type: integer
                  total:
                    type: integer
                  totalPages:
                    type: integer
                  calendars:
                    type: array
                    items:
                      type: object
                      properties:
                        uuid:
                          type: string
                        name:
                          type: string
    post:
      summary: Create a new calendar
      operationId: createCalendar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Calendar created
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  name:
                    type: string
  /calendars/{calendarUuid}:
    get:
      summary: Get single calendar details by UUID
      operationId: getCalendarByUuid
      parameters:
        - name: calendarUuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Calendar details
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  name:
                    type: string
        '404':
          description: Calendar not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    put:
      summary: Update single calendar details
      operationId: updateCalendar
      parameters:
        - name: calendarUuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Calendar updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  name:
                    type: string
        '404':
          description: Calendar not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      summary: Delete single calendar by UUID
      operationId: deleteCalendar
      parameters:
        - name: calendarUuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Calendar deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Calendar not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /calendars/{calendarUuid}/entries:
    post:
      summary: Create a new calendar entry
      operationId: createCalendarEntry
      parameters:
        - name: calendarUuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - start
                - duration
              properties:
                title:
                  type: string
                start:
                  type: string
                  format: date-time
                duration:
                  type: integer
      responses:
        '201':
          description: Calendar entry created
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  title:
                    type: string
                  start:
                    type: string
                    format: date-time
                  duration:
                    type: integer
    get:
      summary: List calendar entries
      operationId: getCalendarEntries
      parameters:
        - name: calendarUuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: start
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: end
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of calendar entries
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries:
                    type: array
                    items:
                      type: object
                      properties:
                        uuid:
                          type: string
                        title:
                          type: string
                        start:
                          type: string
                          format: date-time
                        duration:
                          type: integer
  /calendars/{calendarUuid}/entries/{entryUuid}:
    put:
      summary: Update single calendar entry details
      operationId: updateCalendarEntry
      parameters:
        - name: calendarUuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: entryUuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - start
                - duration
              properties:
                title:
                  type: string
                start:
                  type: string
                  format: date-time
                duration:
                  type: integer
      responses:
        '200':
          description: Calendar entry updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  title:
                    type: string
                  start:
                    type: string
                    format: date-time
                  duration:
                    type: integer
        '404':
          description: Calendar entry not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      summary: Delete single calendar entry by UUID
      operationId: deleteCalendarEntry
      parameters:
        - name: calendarUuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: entryUuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Calendar entry deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Calendar entry not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
