openapi: 3.0.0
info:
  title: Easy Peasy Calendar API
  version: "1.0.0"
  description: API for managing calendars and calendar entries.
paths:
  /calendars:
    get:
      tags:
        - Calendars
      summary: Get list of calendars
      operationId: getCalendars
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  offset:
                    type: integer
                  limit:
                    type: integer
                  total:
                    type: integer
                  totalPages:
                    type: integer
                  calendars:
                    type: array
                    items:
                      type: object
                      properties:
                        uuid:
                          type: string
                        name:
                          type: string
    post:
      tags:
        - Calendars
      summary: Create a new calendar
      operationId: createCalendar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  minLength: 3
                  maxLength: 100
      responses:
        '201':
          description: Calendar created
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  name:
                    type: string
  /calendars/{calendar_uuid}:
    get:
      tags:
        - Calendars
      summary: Get single calendar details by UUID
      operationId: getCalendarByUuid
      parameters:
        - name: calendar_uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Calendar details
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  name:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Calendar not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    put:
      tags:
        - Calendars
      summary: Update single calendar details
      operationId: updateCalendar
      parameters:
        - name: calendar_uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Calendar updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  name:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Calendar not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      tags:
        - Calendars
      summary: Delete single calendar by UUID
      operationId: deleteCalendar
      parameters:
        - name: calendar_uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Calendar deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Calendar not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /calendars/{calendar_uuid}/entries:
    post:
      tags:
        - Calendar Entries
      summary: Create a new calendar entry
      operationId: createCalendarEntry
      parameters:
        - name: calendar_uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - start_date
                - end_date
                - recurrence_rule
              properties:
                title:
                  type: string
                start_date:
                  type: string
                  format: date-time
                end_date:
                  type: string
                  format: date-time
                recurrence_rule:
                  type: string
      responses:
        '201':
          description: Calendar entry created
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  title:
                    type: string
                  start_date:
                    type: string
                    format: date-time
                  end_date:
                    type: string
                    format: date-time
                  recurrence_rule:
                    type: string
    get:
      tags:
        - Calendar Entries
      summary: List calendar entries
      operationId: getCalendarEntries
      parameters:
        - name: calendar_uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: start_date
          description: example 2023-01-01
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: end_date
          description: example 2023-01-10
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of calendar entries
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries:
                    type: array
                    items:
                      type: object
                      properties:
                        uuid:
                          type: string
                        title:
                          type: string
                        start_date:
                          type: string
                          format: date-time
                        end_date:
                          type: string
                          format: date-time
                        recurrence_rule:
                          type: string
  /calendars/{calendar_uuid}/entries/{entry_uuid}:
    put:
      tags:
        - Calendar Entries
      summary: Update single calendar entry details
      operationId: updateCalendarEntry
      parameters:
        - name: calendar_uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: entry_uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: force
          in: query
          required: false
          schema:
            type: string
            default: false
          description: Force update the calendar entry even if it conflicts with existing entries.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - start_date
                - end_date
                - recurrence_rule
              properties:
                title:
                  type: string
                start_date:
                  type: string
                  format: date-time
                end_date:
                  type: string
                  format: date-time
                recurrence_rule:
                  type: string
      responses:
        '204':
          description: Calendar entry updated
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Calendar entry not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      tags:
        - Calendar Entries
      summary: Delete single calendar entry by UUID
      operationId: deleteCalendarEntry
      parameters:
        - name: calendar_uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: entry_uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Calendar entry deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Calendar entry not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
