name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build base Docker image
        run: |
          docker build \
            --target base \
            -t base/calendar-api:latest \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} .
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_PORT: ${{ secrets.API_PORT }}

      - name: Build production Docker image
        run: |
          docker build \
            --target production \
            -t ghcr.io/${{ github.repository }}/calendar-api:latest \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} .
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_PORT: ${{ secrets.API_PORT }}

      - name: Start services with Docker Compose
        run: docker compose up -d
        env:
          COMPOSE_PROJECT_NAME: calendar_project

      - name: Wait for database to be ready
        run: |
          timeout=100
          while ! docker exec database pg_isready -U user -d calendar_db && [ $timeout -gt 0 ]; do
            echo "Waiting for database to be ready..."
            sleep 1
            timeout=$((timeout-1))
          done
          if [ $timeout -eq 0 ]; then
            echo "Database not ready in time"
            exit 1
          fi

      - name: Run tests (production image)
        run: |
          docker run --rm \
            --user 0:0 \
            --network "${{ env.COMPOSE_PROJECT_NAME }}_default" \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e API_PORT=${{ secrets.API_PORT }} \
            ghcr.io/${{ github.repository }}/calendar-api:latest \
            yarn prod:test

      - name: Docker login to GHCR
        if: success()
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Push Docker image to GHCR
        if: success()
        run: docker push ghcr.io/${{ github.repository }}/calendar-api:latest

      - name: Clean up
        run: |
          docker-compose down --volumes
          sudo rm -rf ./.docker/