name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        volumes:
          - postgres_data:/var/lib/postgresql/data

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build production Docker image
        run: docker build --target production -t ghcr.io/${{ github.repository }}/calendar-api:latest .
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_PORT: ${{ secrets.API_PORT }}

      - name: Run tests (production image)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_PORT: ${{ secrets.API_PORT }}

        run: |
          docker compose --profile prod up --build --exit-code-from api_prod
          docker exec api_prod yarn test:prod

      - name: Docker login to GHCR
        if: success()
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Push Docker image to GHCR
        if: success()
        run: docker push ghcr.io/${{ github.repository }}/calendar-api:latest